### ISSUE TITLE
TensorFlow not installed

### ISSUE THREAD

**Issue by alexstaravoitau** [Avsecz/aws-tensorflow-setup#1]
Thanks for the awesome script! Although looks like for me nothing was installed past Anaconda installation. I've followed your tutorial and managed to install TensorFlow manually though. See [full installation log](https://github.com/Avsecz/aws-tensorflow-setup/files/376328/installation_log.txt).

It might be that I've missed something, but I thought I should let you know anyway. Thanks again, the script was of a huge help!

**Comment by Avsecz** [comment]
Hey, I'm glad it helped! Was the cudnn download path correctly specified? I can try to rerun the script on aws to see where it went wrong.

**Comment by Avsecz** [comment]
I fixed the issue. I also added the cudnn download path.

**Comment by alexstaravoitau** [comment]
Ah yes, I think I've specified the path as far as I remember — could be that some whitespace or special character slipped through... 

Anyway, thanks again, I'll be writing a quick blog post about remote access to Jupyter Notebook running on AWS with a couple of shell scripts to do all the starting/stopping routines; I will definitely reference your awesome article and script. 👍

**Comment by Avsecz** [comment]
Thanks! :+1:
